### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by Bebabo10** [terrainwax/LootCrate#2]
http://pastebin.com/8bAFZ8EH

**Comment by terrainwax** [comment]
What is you version of my plugin ?

**Comment by Bebabo10** [comment]
Latest version of the plugin no config changes.

**Comment by terrainwax** [comment]
3.0 ?

**Comment by Bebabo10** [comment]
2.0 and I see you just updated

**Comment by terrainwax** [comment]
2.0 is for API 3.0 and 3.0 is for API 4.0 you have API 4.0 take 3.0 and it will be fix
